### ISSUE TITLE
PHP Engine requirement 

### ISSUE THREAD

**Issue by JesusTheHun** [slope-it/clock-mock#24]
Why PHP 7.1 is declared as not supported ?
I see that `uopz` supports PHP 7.1+ , and nothing in the source code let me think that it's only compatible with PHP 7.4. Is there any particular reason ?

**Comment by asprega** [comment]
Hi!

Since the initial commit we decided to not support (at least not explicitly) PHP versions that were already past end of life (PHP 7.1 EOL was on November 2020).
Currently, PHP 7.4 is the oldest supported version and we will continue to keep it at least until end of life. We do this just to keep our maintenance efforts as low as possible.

The library is not tested with versions older than PHP 7.4, but if you want to try it feel free to either:
- use --ignore-platform-reqs flag with composer executable (https://getcomposer.org/doc/03-cli.md#composer-ignore-platform-req-or-composer-ignore-platform-reqs)
- declare a fake php platform in composer.json (https://getcomposer.org/doc/06-config.md#platform)
- fork this library and update the php minimum requirement

Hope this helps!
