### ISSUE TITLE
Problems with specifying datetime and timezone

### ISSUE THREAD

**Issue by hum2** [slope-it/clock-mock#26]
Hello,
I have a problem that when I create an instance with `$datetime` and `$timezone`, it returns different results from `Datetime`.

Specifically, the case is as follows.
```php
$expectedDatetimeFormat = '1986-06-05 12:13:14';
$timezone = new \DateTimeZone('Asia/Tokyo'); // +09:00

// not mocked Datetime
// This test succeed
$asiaTokyoTimezone = new \DateTime('1986-06-05 12:13:14', $timezone);
$this->assertSame($expectedDatetimeFormat, $asiaTokyoTimezone->format('Y-m-d H:i:s'));

// mocked Datetime
// This test fails
ClockMock::freeze(new \DateTime('2022-11-21 00:00:00'));
$asiaTokyoTimezone = new \DateTime('1986-06-05 12:13:14', $timezone);
$this->assertSame($expectedDatetimeFormat, $asiaTokyoTimezone->format('Y-m-d H:i:s')); // actual: 1986-06-05 21:13:14
```

**Solution:**
Do try to set the `$datetime` with timezone when `__construct`.
In src/DateTimeMock.php:

```php
// ..
if ($datetime !== 'now' && $timezone !== null) {
    $datetime = $datetime . ' ' . $timezone->getName();
}
parent::__construct($datetime, $timezone);
// ...
```

**Comment by asprega** [comment]
Hi and many thanks for your contribution. I investigated the issue a little bit deeper and found that:
- it occurs with any kind of mocked clock (either relative or absolute)
- the issue is present with date constructed with any relative string (not just "now" but also "yesterday", "tomorrow", etc...)

for these reasons I reworked the fix you provided and made a new pull request #28 (BTW, thanks for spending time on it, as it pointed me to the right direction).
I'm about to release a new minor version contaning the fix.

Thanks again!
