### ISSUE TITLE
Does this affect performance if used in production code?

### ISSUE THREAD

**Issue by which1ispink** [slope-it/clock-mock#30]
We have a use case where we need to "mock" date times in production code (not just tests). Would using this library/extension affect the PHP performance? And if so, are there any estimations on the degree of the performance degradation it could cause?

**Comment by asprega** [comment]
Hi. As explained [here](https://dev.to/andreasprega/clockmock-a-convenient-way-to-mock-date-and-time-in-php-5032), we do not recommended using this in production code due to the nature of the uopz extension, that allows modification of php runtime from userland code: https://www.php.net/manual/en/intro.uopz.php.

That said, I have never run any specific benchmark. If I had to do it, I would measure the impact of the uopz extension alone (when enabled) and subsequently eventual impacts of the specific mocking functions you are interested in.

In case you want to look for more "solid" alternatives which require adaptations to your code (which was specifically what we wanted to avoid in our case), you might want to take a look at implementors of the specific PSR-20 Clock interface: https://packagist.org/providers/psr/clock-implementation.

Closing this, feel free to re-open if you need more information. Thanks!
